### PR TITLE
Fix bug in lPKCS11PkMbedtlsCloseSessionAndFree. Add doxygen api docs.

### LINKED ISSUE #877: [BUG] PKCS#11 session close failure during disconnection
**Describe the bug**
It's about mbedtls_pk_pkcs11.c in the dev branch.
Since the following source code is cast with a structure suitable for ECDSA, it fails to close the PKCS#11 session when the key type is RSA.
We believe that you need to cast with a struct that matches the key you are using.
https://github.com/FreeRTOS/FreeRTOS/blob/dev/FreeRTOS-Plus/Source/Application-Protocols/network_transport/mbedtls_pk_pkcs11.c#L326
image

**Target**
- Development board: CK-RX65N
- Instruction Set Architecture: Renesas RX
- IDE and version: e2 studio-2022-10
- Toolchain and version: Renesas CC-RX v3.04.00

**Host**
- Host OS: Windows
- Version: Windows 10

**To Reproduce**
- We built a project for CK-RX65N based on corePKCS11_MQTT_Mutual_Auth_Windows_Simulator.
- An error occurs within the lPKCS11PkMbedtlsCloseSessionAndFree function for closing the connection.

**Expected behavior**
PKCS#11 session close fails when key type is RSA.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by paulbartell**
Description
-----------
Fix a bug in the lPKCS11PkMbedtlsCloseSessionAndFree function which did not work properly with RSA keys.

Add some doxygen api docs for public functions.

Fix #877 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: FreeRTOS-Plus/Source/Application-Protocols/network_transport/mbedtls_pk_pkcs11.c [hunk 1]
```diff
@@ -1020,7 +1137,12 @@ static CK_RV p11_rsa_ctx_init( void * pvCtx,
         xResult = CKR_FUNCTION_FAILED;
     }
 
-    /* / * Initialize public RSA parameter data from attributes * / */
+    /*
+     * TODO: corePKCS11 does not allow exporting RSA public attributes.
+     * This function should be updated to properly initialize the
+     * mbedtls_rsa_context when this addressed.
```
Comment (jasonpcarroll) [inline FreeRTOS-Plus/Source/Application-Protocols/network_transport/mbedtls_pk_pkcs11.c:1143]:
```suggestion
     * mbedtls_rsa_context when this is addressed.
```

File: FreeRTOS-Plus/Source/Application-Protocols/network_transport/mbedtls_pk_pkcs11.c [hunk 2]
```diff
@@ -73,15 +74,51 @@ typedef struct P11RsaCtx
...
 static void * p11_ecdsa_ctx_alloc( void );
 
+/**
+ * @brief Initializes a P11EcDsaCtx_t with the given PKCS11 parameters.
+ *
+ * @param pvCtx Void pointer to the P11EcDsaCtx_t.
+ * @param pxFunctionList Pointer to a CK_FUNCTION_LIST for the PKCS11 module.
+ * @param xSessionHandle An initialized CK_SESSION_HANDLE for the given PKCS11 module.
+ * @param xPkHandle The CK_OBJECT_HANDLE for the target private key.
+ * @return CK_RV
```
Comment (jasonpcarroll) [inline FreeRTOS-Plus/Source/Application-Protocols/network_transport/mbedtls_pk_pkcs11.c:93]: Should the return comment be more explicit? I'm not sure what a CK_RV is, but if someone more familiar can understand what this means, then this can be left.

File: FreeRTOS-Plus/Source/Application-Protocols/network_transport/mbedtls_pk_pkcs11.c [hunk 3]
```diff
@@ -111,7 +175,6 @@ static int p11_ecdsa_check_pair( const void * pvPub,
 static void p11_ecdsa_debug( const void * pvCtx,
                              mbedtls_pk_debug_item * pxItems );
 
-/* Helper functions */
 static int prvEcdsaSigToASN1InPlace( unsigned char * pucSig,
```
Comment (jasonpcarroll) [inline FreeRTOS-Plus/Source/Application-Protocols/network_transport/mbedtls_pk_pkcs11.c:178]: why are these functions / several below not documented with doxygen?

File: FreeRTOS-Plus/Source/Application-Protocols/network_transport/mbedtls_pk_pkcs11.c (hunk 1 above)
Comment (jasonpcarroll) [reply FreeRTOS-Plus/Source/Application-Protocols/network_transport/mbedtls_pk_pkcs11.c:1143]: Is this clearly documented anywhere other than just this comment?

File: FreeRTOS-Plus/Source/Application-Protocols/network_transport/mbedtls_pk_pkcs11.h [hunk 4]
```diff
@@ -34,14 +34,40 @@
...
 int lPKCS11PkMbedtlsCloseSessionAndFree( mbedtls_pk_context * pxMbedtlsPkCtx );
 
+/**
+ * @brief Callback to generate random data with the PKCS11 module.
+ *
+ * @param[in] pvCtx void pointer to the
+ * @param[in] pucRandom Byte array to fill with random data.
+ * @param[in] xRandomLength Length of byte array.
+ *
+ * @return Zero on success.
```
Comment (jasonpcarroll) [inline FreeRTOS-Plus/Source/Application-Protocols/network_transport/mbedtls_pk_pkcs11.h:65]:
```suggestion
 * @return 0 on success.
```
nitpick for consistency.

File: FreeRTOS-Plus/Source/Application-Protocols/network_transport/mbedtls_pk_pkcs11.c (hunk 3 above)
Comment (paulbartell) [reply FreeRTOS-Plus/Source/Application-Protocols/network_transport/mbedtls_pk_pkcs11.c:178]: The names a pretty self explanatory :)

File: FreeRTOS-Plus/Source/Application-Protocols/network_transport/mbedtls_pk_pkcs11.c (hunk 1 above)
Comment (paulbartell) [reply FreeRTOS-Plus/Source/Application-Protocols/network_transport/mbedtls_pk_pkcs11.c:1143]: Nope. RSA is really not well supported by corePKCS11 other than basic signature operations.

**Review by jasonpcarroll — APPROVED** [review]
